stages:
  get_data:
    cmd: dvc pull PokemonData
    outs:
    - PokemonData
  train_val_split:
    cmd: python src/train_val_split.py
    deps:
    - src/train_val_split.py
    - PokemonData
    outs:
    - data
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data
    outs:
    - accuracy.png
    - loss.png
    - precision.png
    - recall.png
    - auc.png
