name: Deploy App
on:
  push:
    branches:
      - master

jobs:
  deploy_app:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.16
          cache: pip
      
      - name: Cache
        uses: actions/cache@v2
        