name: train model
on: [push]
jobs:
  train-and-report:
    runs-on: [self-hosted, cml-gpu]
    steps:
      - uses: actions/checkout@v3
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md


          cml-send-comment report.md

