name: train model
on: [push]
jobs:
  train-and-report:
    defaults:
        run:
          shell: bash -l {0}
    runs-on: [self-hosted, cml-gpu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          python-version: '3.9'
      - name: Create and activate conda environment
        run: |
          conda env create -f environment.yml

      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          conda activate tf
          dvc pull --run-cache
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md master > report.md

          cml-send-comment report.md

