name: train model
on: [push]
jobs:
  train-and-report:
    runs-on: [self-hosted, cml-gpu]
    steps:
      - uses: actions/checkout@v3
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh

          conda create --name mlops --file requirements.txt
          conda install --name mlops --file requirements.txt
          conda activate mlops

          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md


          cml-send-comment report.md

